### ISSUE TITLE
[Bug] Images with a space in their name are not correctly encoded

### ISSUE THREAD

**Issue by martpie** [sveltia/sveltia-cms#515]
If you upload an image that is name for example 

```
screenshot (2).png
```

the created markdown will be

```
![](/uploads/screenshot (2).png)
```

Problem is markdown parsers (like `react-markdown`) will not be able to parse that due to the space (and/or parenthesis?), and a website will typically display:

<img width="753" height="256" alt="Image" src="https://github.com/user-attachments/assets/4905b455-81ce-4dd4-a0e3-9e70d6388140" />

**Comment by kyoshino** [comment]
[Which version](https://github.com/sveltia/sveltia-cms#showing-the-cms-version) are you using? This issue was reported in #514 and solved in [v0.106.3](https://github.com/sveltia/sveltia-cms/releases/tag/v0.106.3). If you’ve installed the CMS via npm, please update the package. Otherwise, you just need to reload the CMS.

**Comment by martpie** [comment]
The deployed version was 0.100, will update

**Comment by MarioWindsor** [comment]
@kyoshino — I have the same issue (screenshot below). 

---

<img width="813" height="273" alt="Image" src="https://github.com/user-attachments/assets/10f773ec-72c8-4ba1-91b9-d1c44ef77593" />

---

I dont know what you mean by "reload the CMS". I understand this issue has been resolved in newer versions, **any assistance would be appreciated.** I have NOT installed the CMS via npm. I'm developing the website using 11ty, and deploying it via Netlify. Previously this was running on Decap CMS but i have replaced that script with the following. I think it's fetching the latest version of sveltia cms@0.109.0

Here's what my admin index file looks like:

<img width="1193" height="468" alt="Image" src="https://github.com/user-attachments/assets/14cf96df-f649-4435-a4c5-995cc7714235" />

---

... and here's some of the config file for your reference (I have hidden the repo)

<img width="954" height="877" alt="Image" src="https://github.com/user-attachments/assets/da7e9c66-99f5-41e4-b5b6-5e221e68b953" />

Cheers.

**Comment by kyoshino** [comment]
@MarioWindsor  “reload the CMS” means you need reload the browser tab to load the latest version of `sveltia-cms.js` from unpkg. Otherwise the script is cached in the browser and the issue may persist.

I’ll check why the previous fix isn’t working.

**Comment by MarioWindsor** [comment]
@kyoshino — thank you for the clarification. I have done "empty cache and hard reload".

<img width="543" height="248" alt="Image" src="https://github.com/user-attachments/assets/9e24364e-1dc0-4a63-a548-5921379bc4ea" />

Followed by adding a new screenshot to the media directory and including it in my blog article. Although the issue still persists. Please Note: the last line is the new image added just now.

<img width="895" height="435" alt="Image" src="https://github.com/user-attachments/assets/c6216f6e-f999-4a58-9c2e-258923a521ef" />

EDIT: Sometimes I notice this `<0x202f>` character instead of a space. Could that have anything to do with it?

<img width="844" height="217" alt="Image" src="https://github.com/user-attachments/assets/9b19874a-8220-4fb1-bc3c-ecd1538b9234" />

**Comment by kyoshino** [comment]
Yes, I have realized that there is a no-break space in filenames. Apparently, this is the standard filename convention when taking a screenshot on macOS. For some reason, the no-break space in your first file path `2025-09-30...` has been converted to a normal space. However, even in that case, the preview pane should render an `<img>` tag with a broken image instead of a raw Markdown text. I’m checking how it could happen.

**Comment by kyoshino** [comment]
Ah wait, this screenshot is from your site, not the preview pane of the CMS.

> <img alt="Image" width="813" height="273" src="https://private-user-images.githubusercontent.com/5945762/496840662-10f773ec-72c8-4ba1-91b9-d1c44ef77593.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTk0NDIwMDAsIm5iZiI6MTc1OTQ0MTcwMCwicGF0aCI6Ii81OTQ1NzYyLzQ5Njg0MDY2Mi0xMGY3NzNlYy03MmM4LTRiYTEtOTFiOS1kMWM0NGVmNzc1OTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MTAwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTEwMDJUMjE0ODIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODRhMTE5YmQwZDE1YmM4MzYwMTVkYjM4ODVlMDhjMDUzMTkwYTE5NmE0M2E1NTJhMmVkOGVkYzBmYjljN2RlMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.T01gidW8mqr90lN_IC5aO5aBgAYJBCuf4WEus8p8S88">

And I’ve just realized that the CMS has indeed a bug: when you upload directly to the markdown field, the spaces are properly encoded to `%20`, but it doesn’t work when you select an existing file from the Select Image dialog. I’ll fix it now.

**Comment by kyoshino** [comment]
> And I’ve just realized that the CMS has indeed a bug: when you upload directly to the markdown field, the spaces are properly encoded to `%20`, but it doesn’t work when you select an existing file from the Select Image dialog. I’ll fix it now.

Fixed the issue in [v0.109.1](https://github.com/sveltia/sveltia-cms/releases/tag/v0.109.1).

The CMS won’t replace paths already added on markdown so please replace any normal spaces with `%20` manually. (No-break spaces should be kept.) Newly inserted images should no longer have this problem. No-break spaces are also now normalized as normal spaces when you upload new images.

**Comment by MarioWindsor** [comment]
### @kyoshino — can confirm it is working now. 🥳 🚀 🎉

**You're doing amazing work 🙌 . Thank you so much!!!**

_I'm so glad to have found Sveltia CMS as an alternative to Dcap CMS._

<img width="1092" height="406" alt="Image" src="https://github.com/user-attachments/assets/57ecf155-a011-4e45-ab5c-4e9336a92eed" />

Cheers 🍻
